title: "Mounifolio"
author: "Mounib Benimam"
description: "A blog about image processing and Machine Learning, where i casualy write about what intreagues me and i find interesting" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "mounib.benimam@outlook.com"
twitter_username: "twitteruser"
github_username: "mbeni12333"
linkedin_username: "mounib-benimam"

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
    input: GFM
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postfiles
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
